providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20"]
cmds = ["npm install -g pnpm@9.15.4"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_Zmx1ZW50LXN3YW4tOTYuY2xlcmsuYWNjb3VudHMuZGV2JA pnpm --filter @aegis/web build"]

[start]
cmd = "pnpm --filter @aegis/web start"
