[build]
builder = "DOCKERFILE"
dockerfilePath = "services/control-plane/Dockerfile"

[deploy]
healthcheckPath = "/health/ready"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
numReplicas = 1
